export { default as Aristotle } from './by_author/Aristotle'
export { default as ArthurSchopenhauer } from './by_author/ArthurSchopenhauer'
export { default as BoYinRa } from './by_author/BoYinRa'
export { default as CarlGustavJung } from './by_author/CarlGustavJung'
export { default as EckhartTolle } from './by_author/EckhartTolle'
export { default as GrantCardone } from './by_author/GrantCardone'
export { default as JidduKrishnamurti } from './by_author/JidduKrishnamurti'
export { default as JimRohn } from './by_author/JimRohn'
export { default as RobertGreene } from './by_author/RobertGreene'
export { default as SigmundFreud } from './by_author/SigmundFreud'
export { default as SriRamanaMaharishi } from './by_author/SriRamanaMaharishi'
export { default as SriNisargadattaMaharaj } from './by_author/SriNisargadattaMaharaj'
export { default as UnknownAuthor } from './by_author/UnknownAuthor.ts'

export { default as english } from './english'
